# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,32,7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr = np.array([3,6,32,7], np.int64)

In [5]:
myarr

array([ 3,  6, 32,  7], dtype=int64)

In [6]:
myarr = np.array([[3,6,32,7]], np.int64)

In [7]:
myarr[0, 1]

6

In [8]:
myarr.shape

(1, 4)

In [9]:
myarr.dtype

dtype('int64')

In [10]:
myarr[0, 1] = 45

In [11]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

# Array creation: Conversion from other Python structures

In [12]:
listarray = np.array([[1,2,3], [5, 8, 5],[0,3,1]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [14]:
listarray.dtype

dtype('int32')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [18]:
zeros = np.zeros((2,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.dtype

dtype('float64')

In [21]:
zeros.shape

(2, 5)

In [22]:
rng = np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,5,12)

In [25]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
lspace = np.linspace(1,50,10)

In [27]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
lspace = np.linspace(1,4,4)

In [29]:
lspace

array([1., 2., 3., 4.])

In [30]:
lspace = np.linspace(1,5,4)

In [31]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [32]:
emp = np.empty((4,6))

In [33]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 1.42421160e-306, 6.23055651e-307,
        2.22522597e-306, 1.06810268e-306, 6.23052935e-307],
       [7.56595733e-307, 1.37961302e-306, 8.34451503e-308,
        1.78022342e-306, 8.06635958e-308, 8.34423493e-308]])

In [34]:
emp_like = np.empty_like(lspace)

In [35]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [36]:
ide = np.identity(45)

In [37]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [38]:
ide.shape

(45, 45)

In [39]:
arr = np.arange(99)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.shape

(99,)

In [44]:
x = [[1,2,3], [4,5,6],[7,1,0]]

In [45]:
ar = np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [48]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [49]:
ar.flat

In [50]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [51]:
ar.ndim

2

In [52]:
ar.size

9

In [53]:
ar.nbytes

36

In [54]:
one = np.array([1,3,4,634,2])

In [59]:
one.argmax

<function ndarray.argmax>

In [69]:
one.argmax()

3

In [70]:
one.argmin()

0

In [71]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
ar.argsort

<function ndarray.argsort>

In [74]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [75]:
ar.argmin

<function ndarray.argmin>

In [76]:
ar.argmin()

8

In [77]:
ar.argmax

<function ndarray.argmax>

In [78]:
ar.argmax()

6

In [79]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [80]:
ar.argmax()

6

In [81]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [82]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [83]:
ar.argsort

<function ndarray.argsort>

In [84]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [85]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [86]:
ar.ravel

<function ndarray.ravel>

In [87]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [88]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
ar2 = np.array([[1, 4, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [91]:
ar + ar2

array([[ 2,  6,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [92]:
[324, 34] + [34, 546]

[324, 34, 34, 546]

In [93]:
ar * ar2

array([[ 1,  8,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [94]:
ar2

array([[1, 4, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [95]:
ar*ar2

array([[ 1,  8,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [96]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [97]:
ar.sum

<function ndarray.sum>

In [98]:
ar.sum()

29

In [100]:
ar.max

<function ndarray.max>

In [101]:
ar.max()

7

In [102]:
ar.min

<function ndarray.min>

In [103]:
ar.min()

0

In [104]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [105]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [106]:
type(np.where(ar>5))

tuple

In [107]:
np.count_nonzero(ar)

8

In [ ]:
np.count_nonzero(ar)